version: '3.7'

volumes:
  local-links-manager-tmp:
  local-links-manager-node-modules:

x-local-links-manager: &local-links-manager
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: local-links-manager
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - local-links-manager-tmp:/govuk/local-links-manager/tmp
    - local-links-manager-node-modules:/govuk/local-links-manager/node_modules
  working_dir: /govuk/local-links-manager

services:
  local-links-manager-lite:
    <<: *local-links-manager
    shm_size: 512mb
    depends_on:
      - postgres-13
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/local-links-manager"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/local-links-manager-test"
      REDIS_URL: redis://redis

  local-links-manager-app:
    <<: *local-links-manager
    depends_on:
      - postgres-13
      - nginx-proxy
      - redis
    environment:
      DATABASE_URL: "postgresql://postgres@postgres-13/local-links-manager"
      REDIS_URL: redis://redis
      VIRTUAL_HOST: local-links-manager.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
