version: '3.7'

x-email-alert-service: &email-alert-service
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: email-alert-service
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
  working_dir: /govuk/email-alert-service

services:
  email-alert-service-lite:
    <<: *email-alert-service
    depends_on:
      - redis
      - rabbitmq
    environment:
      REDIS_URL: redis://redis
      RABBITMQ_HOSTS: rabbitmq
      RABBITMQ_VHOST: /
      RABBITMQ_USER: guest
      RABBITMQ_PASSWORD: guest
