version: '3.7'

x-generic-ruby-library: &generic-ruby-library
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: generic-ruby-library
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root

services:
  gds-api-adapters-lite:
    <<: *generic-ruby-library
    working_dir: /govuk/gds-api-adapters

  govspeak-lite:
    <<: *generic-ruby-library
    working_dir: /govuk/govspeak

  govuk_app_config-lite:
    <<: *generic-ruby-library
    working_dir: /govuk/govuk_app_config

  govuk-docker-lite:
    <<: *generic-ruby-library
    working_dir: /govuk/govuk-docker

  plek-lite:
    <<: *generic-ruby-library
    working_dir: /govuk/plek

  smokey-lite:
    <<: *generic-ruby-library
    working_dir: /govuk/smokey
    environment:
      NO_SANDBOX: "true"
    shm_size: 512mb
