version: '3.7'

volumes:
  authenticating-proxy-tmp:

x-authenticating-proxy: &authenticating-proxy
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: authenticating-proxy
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - authenticating-proxy-tmp:/govuk/authenticating-proxy/tmp
  working_dir: /govuk/authenticating-proxy

services:
  authenticating-proxy-lite:
    <<: *authenticating-proxy
    depends_on:
      - postgres-14
    environment:
      GOVUK_UPSTREAM_URI: http://government-frontend.dev.gov.uk
      DATABASE_URL: "postgresql://postgres@postgres-14/authenticating-proxy"
      TEST_DATABASE_URL: "postgresql://postgres@postgres-14/authenticating-proxy-test"

  authenticating-proxy-app: &authenticating-proxy-app
    <<: *authenticating-proxy
    depends_on:
      - postgres-14
      - nginx-proxy
      - government-frontend-app
    environment:
      GOVUK_UPSTREAM_URI: http://government-frontend.dev.gov.uk
      DATABASE_URL: "postgresql://postgres@postgres-14/authenticating-proxy"
      VIRTUAL_HOST: authenticating-proxy.dev.gov.uk
      BINDING: 0.0.0.0
    expose:
      - "3000"
    command: bin/rails s --restart
