version: '3.7'

volumes:
  content-store-tmp:

x-content-store: &content-store
  build:
    context: .
    dockerfile: Dockerfile.govuk-base
  image: content-store
  stdin_open: true
  tty: true
  volumes:
    - ${GOVUK_ROOT_DIR:-~/govuk}:/govuk:delegated
    - root-home:/root
    - content-store-tmp:/govuk/content-store/tmp
  working_dir: /govuk/content-store

services:
  content-store-lite:
    <<: *content-store
    depends_on:
      - postgres-13
    environment:
      TEST_DATABASE_URL: "postgresql://postgres@postgres-13/content-store-test"
      DATABASE_URL: "postgresql://postgres@postgres-13/content-store"

  content-store-app: &content-store-app
    <<: *content-store
    depends_on:
      - router-api-app
      - nginx-proxy
      - postgres-13
    environment:
      MONGODB_URI: "mongodb://mongo-3.6/content-store"
      VIRTUAL_HOST: content-store.dev.gov.uk
      BINDING: 0.0.0.0
      DATABASE_URL: "postgresql://postgres@postgres-13/content-store"
      
    expose:
      - "3000"
    command: bin/rails s --restart
